apps/persona/urls.py
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path('listar_empledos/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('listar_by_area/<shorname>/', views.ListByAreaEmpleado.as_view(),name="empleados_area"),
    path('listar_empleados_admin/', views.ListEmpleadosAdmin.as_view(),name="lista_empleados_admin"),
    path('buscar-empleado/', views.ListEmpleadosByKwordListView.as_view()),
    path('listar_habilidades/', views.ListHabilidadesView.as_view()),
    # Details View
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name="empleado_detail"),
    # Create View
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name="empleado_add"),
    # Template View
    path('success/', views.SuccessTemplateView.as_view(), name="success"),
    # Update View
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name="update-empleado"),
    # Delete View
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name="delete-empleado"),
    path('', views.InicioView.as_view(), name="inicio"),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('apps.departamento.urls')),
    re_path('',include('apps.home.urls')),
    re_path('',include('apps.persona.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/persona/models.py
from django.db import models
from apps.departamento.models import Departamento

# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleados'
    
    def __str__(self):
        return f'{self.id} - {self.habilidad}'


class Empleado(models.Model):
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('Apellidos', max_length=50)
    full_name = models.CharField(
        'Nombres completos', 
        max_length=120,
        blank=True
    )
    job = models.CharField(
        'Trabajo', 
        max_length=1,
        choices=JOB_CHOICES
    )
    departamento = models.ForeignKey(
        Departamento, 
        on_delete=models.CASCADE
    )
    avatar = models.ImageField(upload_to="empleado", blank=True, null = True)
    Habilidades = models.ManyToManyField(
        Habilidades
    )

    class Meta:
        verbose_name = 'Mi empleado'
        verbose_name_plural = 'Empleados de la empresa'

    def __str__(self):
        return f'{self.id} - {self.first_name} - {self.last_name}'

apps/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            "first_name",
            "last_name",
            "job",
            "departamento",
            "avatar",
            "Habilidades"
        )
        widgets = {
            "Habilidades": forms.CheckboxSelectMultiple()
        }

        

apps/persona/views.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from apps.persona import models

from .forms import EmpleadoForm

# Listar los empleados

class ListAllEmpleados(ListView):
    # model = models.Empleado
    paginate_by = 3
    ordering = 'first_name'
    template_name = "persona/list_all.html"
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword","")
        if palabra_clave:
            lista = models.Empleado.objects.filter(
                Q(first_name__icontains = palabra_clave) | 
                Q(last_name__icontains = palabra_clave)
            )
        else:
            lista = models.Empleado.objects.all()
        return lista


class ListEmpleadosAdmin(ListView):
    # model = models.Empleado
    paginate_by = 10
    ordering = 'id'
    template_name = "persona/lista_empleados.html"
    context_object_name = 'empleados'
    model = models.Empleado

# Listar los empleados por area
class ListByAreaEmpleado(ListView):
    template_name = "persona/list_by_area.html"
    context_object_name = 'empleados'
    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = models.Empleado.objects.filter(
            departamento__shor_name = area
        )
        return lista

# Listar los empleados por palabra clave

class ListEmpleadosByKwordListView(ListView):
    """ Lista empleados por palabra clave """
    template_name = "persona/by_kword.html"
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword","")
        print("*************LLEGA")
        lista = models.Empleado.objects.filter(
            first_name = palabra_clave
        )
        return lista

# Listar habilidades de un empleado

class ListHabilidadesView(ListView):
    template_name = "persona/habilidades.html"
    context_object_name = "habilidades"

    def get_queryset(self):
        empleado = models.Empleado.objects.get(id=6)
        return empleado.Habilidades.all()


class EmpleadoDetailView(DetailView):
    model = models.Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context



class SuccessTemplateView(TemplateView):
    template_name = "persona/success.html"



class EmpleadoCreateView(CreateView):
    model = models.Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForm
    # fields = ('__all__')
    success_url = reverse_lazy('persona_app:lista_empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit = False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super().form_valid(form)


# Actualizar un empleado
class EmpleadoUpdateView(UpdateView):
    model = models.Empleado
    template_name = "persona/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'Habilidades'
    ]
    success_url = reverse_lazy('persona_app:lista_empleados_admin')

    def post(self,request,*args,**kwargs):
        self.object = self.get_object()
        print("*********METHOD POST**************")
        print(request.POST)
        return super().post(request,*args,**kwargs)

    def form_valid(self, form):
        print("*********METHOD FORM VALUE**************")
        print("***********************")
        return super().form_valid(form)



# Eliminar 
class EmpleadoDeleteView(DeleteView):
    model = models.Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:lista_empleados_admin')



class InicioView(TemplateView):
    """ Vista que carga la pagina de inicio """
    template_name = "inicio.html"

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
Registrar empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Registrar Empleado</div>
        <form method="POST" enctype="multipart/form-data" class="cell grid-x grid-margin-x">
            {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{ form.first_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido:
                    {{ form.last_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{ form.job }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Habilidades:
                    {{ form.Habilidades }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Imagen:
                    {{ form.avatar }}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %} 

templates/persona/by_kword.html
<h2>Buscar empleados por palabra clave!!</h2>

<form method="GET">
    {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese el nombre">
    <button type="submit">Buscar</button>
</form>


<h3>Lista resultados</h3>

<ul>
    
    {% for i in empleados %}
       <li>{{ i.first_name }}</li> 
    {% endfor %}
        
</ul>

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
Eliminar empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1>Eliminar empleado: {{ object.first_name }}</h1>
        <form class="cell" method="POST">
            {% csrf_token %}
            <div class="callout">
                <h5>¿Desea eliminar este empleado?</h5>
                <p>Confirmar que desea eliminar</p>
                <button type="submit" class="submit alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <h1>{{ object.titulo }}</h1>
{% endblock title %}
    

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell card-large-4" style="width: 300px; margin-top: 40px;">
                <div class="card-divider">
                  {{ empleado.get_job_display }}
                </div>
                
                {% if empleado.avatar %}
                  <img src="{{ empleado.avatar.url  }}">
                {% else %}
                  <img src="{% static 'images/profile.jpg' %}">
                {% endif %}
                  
                <div class="card-section">
                  <h4>{{ empleado.full_name }}</h4>
                  <p>{{ empleado.first_name }}</p>
                  <p>{{ empleado.departamento.shor_name }}</p>
                  <p><span class="label">Habilidades:</span></p>
                  <ul class="vertical menu">
                      
                      {% for h in empleado.Habilidades.all %}
                        <li>
                          {{ h.habilidad }}
                        </li>
                      {% endfor %}
                        
                  </ul>
                </div>
              </div>
        </div>
    </div>
    
{% endblock content %}
    

{{ empleado }}

<h3>Todos los datos</h3>
<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.job }}</p>
<p>{{ empleado.departamento }}</p>

templates/persona/habilidades.html
<h1>Habilidades del empleado!!</h1>

<ul>
    
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Listar empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">
            {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado" name="" id="">
            </div>
            <div class="cell large-2">
                <button class="submit success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>

                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td><a href="{% url 'persona_app:empleado_detail' empleado.id %}" class="button">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                            </li>
                        {% endif %}
                            
                        
                        {% for pagina in paginator.page_range %}
                            {% ifequal  pagina page_obj.number %} 
                            <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                            <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>  
                            {% else %}
                            <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                            {% endifequal %}
                        {% endfor %}
                            
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}


        </div>
    </div>
    <ul>

        <!-- {% for empleado in object_list %}
        <li>{{ empleado.first_name }} {{ empleado.second_name }}</li>
        {% endfor %} -->

    </ul>
</div>

{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
Lista empleados por departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">
            Empleados por area
        </h2>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>

                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td><a href="#" class="button">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Listar empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>

                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td>
                            <a href="{% url 'persona_app:update-empleado' empleado.id %}" class="button success">Editar</a>
                        </td>
                        <td>
                            <a href="{% url 'persona_app:delete-empleado' empleado.id %}" class="button alert">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                    </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}
                    {% ifequal pagina page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                    <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                    {% else %}
                    <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                    {% endifequal %}
                    {% endfor %}


                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}


        </div>
    </div>
    <ul>

        <!-- {% for empleado in object_list %}
        <li>{{ empleado.first_name }} {{ empleado.second_name }}</li>
        {% endfor %} -->

    </ul>
</div>

{% endblock content %}

templates/persona/success.html
<h1>Felicitaciones se ha creado correctamente el empleado!!</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
Editar empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">
                {% csrf_token %}

                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades:
                        {{ form.Habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="submit success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}