apps/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamentos_app'

urlpatterns = [
    path('new_departamento/',views.NewDepartamento.as_view(),name="nuevo_departamento"),
    path('departamento-lista/',views.DepartamentoListView.as_view(),name="listar_departamento"),
]

apps/persona/urls.py
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path('listar_empledos/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('listar_by_area/<shorname>/', views.ListByAreaEmpleado.as_view(),name="empleados_area"),
    path('listar_empleados_admin/', views.ListEmpleadosAdmin.as_view(),name="lista_empleados_admin"),
    path('buscar-empleado/', views.ListEmpleadosByKwordListView.as_view()),
    path('listar_habilidades/', views.ListHabilidadesView.as_view()),
    # Details View
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name="empleado_detail"),
    # Create View
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name="empleado_add"),
    # Template View
    path('success/', views.SuccessTemplateView.as_view(), name="success"),
    # Update View
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name="update-empleado"),
    # Delete View
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name="delete-empleado"),
    path('', views.InicioView.as_view(), name="inicio"),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('apps.departamento.urls')),
    re_path('',include('apps.home.urls')),
    re_path('',include('apps.persona.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamentos_app:listar_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:lista_empleados_admin' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar nuevo</a></li>
      </ul>
    </div>
  </div>