apps/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamentos_app'

urlpatterns = [
    path('new_departamento/',views.NewDepartamento.as_view(),name="nuevo_departamento"),
    path('departamento-lista/',views.DepartamentoListView.as_view(),name="listar_departamento"),
]

apps/persona/urls.py
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path('listar_empledos/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('listar_by_area/<shorname>/', views.ListByAreaEmpleado.as_view(),name="empleados_area"),
    path('listar_empleados_admin/', views.ListEmpleadosAdmin.as_view(),name="lista_empleados_admin"),
    path('buscar-empleado/', views.ListEmpleadosByKwordListView.as_view()),
    path('listar_habilidades/', views.ListHabilidadesView.as_view()),
    # Details View
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name="empleado_detail"),
    # Create View
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name="empleado_add"),
    # Template View
    path('success/', views.SuccessTemplateView.as_view(), name="success"),
    # Update View
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name="update-empleado"),
    # Delete View
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name="delete-empleado"),
    path('', views.InicioView.as_view(), name="inicio"),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('apps.departamento.urls')),
    re_path('',include('apps.home.urls')),
    re_path('',include('apps.persona.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField(
        'Nombre', 
        max_length=50,
        blank=True
    )
    shor_name = models.CharField(
        'Nombre corto', 
        max_length=50,
        unique=True
    )
    anulate = models.BooleanField(
        'Anulado',
        default=False,
        editable=False
    )

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return f'{self.id} - {self.name} - {self.shor_name}'

apps/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

apps/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import (
    ListView
)
from .forms import NewDepartamentoForm
from apps.persona.models import Empleado
from .models import Departamento
# Create your views here.



class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"


class NewDepartamento(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'


    def form_valid(self, form):
        dep = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        dep.save()
        data = {
            'first_name': form.cleaned_data['nombre'],
            'last_name':form.cleaned_data['apellidos'],
            'job':'1',
            'departamento':dep
        }
        Empleado.objects.create(**data)
        return super().form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}



{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Listar Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                            <tr>
                                <td>{{ departamento.name }}</td>
                                <td>{{ departamento.shor_name }}</td>
                                <td><a href="{% url 'persona_app:empleados_area' departamento.shor_name %}" class="button">Ver empleados</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    
    

templates/departamento/new_departamento.html
<h2>New departamento</h2>


<form method="POST">
    {% csrf_token %}
    <h3>Datos empleado</h3>
    <p>
        {{ form.nombre }}
    </p>
    <p>
        {{ form.apellidos }}
    </p>
    <h3>Datos Departamento</h3>
    <p>
        {{ form.departamento }}
    </p>
    <p>
        {{ form.shorname }}
    </p>
    <button type="submit">Guardar</button>
</form>